parameters:
#    rent_bike.example.class: RentBike\RentBikeBundle\Example

services:
#    rent_bike.example:
#        class: %rent_bike.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
